=== ballaaaa6/boardoffice/SCHEMA/IDENTITY/identity_alias_index.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "gds_character_identity_alias_index_v1",
  "type": "object",
  "additionalProperties": false,
  "required": ["schema", "character_count", "normalization", "aliases"],
  "properties": {
    "schema": {"const": "gds_character_identity_alias_index_v1"},
    "character_count": {"const": 302},
    "normalization": {
      "type": "object",
      "additionalProperties": false,
      "required": ["text", "numeric", "fuzzy_matching"],
      "properties": {
        "text": {"const": "strip_then_casefold"},
        "numeric": {"const": "base10_integer"},
        "fuzzy_matching": {"const": false}
      }
    },
    "aliases": {
      "type": "object",
      "additionalProperties": false,
      "required": ["character_no", "character_code", "full_name", "nickname", "character_id"],
      "properties": {
        "character_no": {"$ref": "#/$defs/aliasMap"},
        "character_code": {"$ref": "#/$defs/aliasMap"},
        "full_name": {"$ref": "#/$defs/aliasMap"},
        "nickname": {"$ref": "#/$defs/aliasMap"},
        "character_id": {"$ref": "#/$defs/aliasMap"}
      }
    }
  },
  "$defs": {
    "aliasMap": {
      "type": "object",
      "minProperties": 302,
      "maxProperties": 302,
      "additionalProperties": {"type": "string", "pattern": "^(TP|RND_[MF])_[0-9]{3}$"}
    }
  }
}

=== ballaaaa6/boardoffice/CHARACTER/IDENTITY/CHARACTERS/identity_alias_index.json
{
  "schema": "gds_character_identity_alias_index_v1",
  "character_count": 302,
  "normalization": {
    "text": "strip_then_casefold",
    "numeric": "base10_integer",
    "fuzzy_matching": false
  },
  "aliases": {
    "character_no": {
      "0": "TP_000",
      "1": "TP_001",
      "2": "TP_002",
      "3": "TP_003",
      "4": "TP_004",
      "5": "TP_005",
      "6": "TP_006",
      "7": "TP_007",
      "8": "TP_008",
      "9": "TP_009",
      "10": "TP_010",
      "11": "TP_011",
      "12": "TP_012",
      "13": "TP_013",
      "14": "TP_014",
      "15": "TP_015",
      "16": "TP_016",
      "17": "TP_017",
      "18": "TP_018",
      "19": "TP_019",
      "20": "TP_021",
      "21": "TP_022",
      "22": "TP_023",
      "23": "TP_024",
      "24": "TP_025",
      "25": "TP_026",
      "26": "TP_027",
      "27": "TP_030",
      "28": "TP_031",
      "29": "TP_033",
      "30": "TP_034",
      "31": "TP_036",
      "32": "TP_038",
      "33": "TP_039",
      "34": "TP_041",
      "35": "TP_042",
      "36": "TP_043",
      "37": "TP_046",
      "38": "TP_047",
      "39": "TP_048",
      "40": "TP_049",
      "41": "TP_070",
      "42": "TP_071",
      "43": "TP_072",
      "44": "TP_073",
      "45": "TP_074",
      "46": "TP_075",
      "47": "TP_076",
      "48": "TP_077",
      "49": "TP_078",
      "50": "TP_079",
      "51": "TP_080",
      "52": "TP_081",
      "53": "TP_082",
      "54": "TP_083",
      "55": "TP_084",
      "56": "TP_085",
      "57": "TP_086",
      "58": "TP_087",
      "59": "TP_088",
      "60": "TP_089",
      "61": "TP_091",
      "62": "TP_093",
      "63": "TP_094",
      "64": "RND_M_148",
      "65": "RND_M_131",
      "66": "RND_M_135",
      "67": "RND_M_001",
      "68": "RND_M_147",
      "69": "RND_F_072",
      "70": "RND_M_103",
      "71": "RND_M_066",
      "72": "RND_F_078",
      "73": "RND_M_062",
      "74": "RND_F_026",
      "75": "RND_M_128",
      "76": "RND_M_162",
      "77": "RND_F_033",
      "78": "RND_M_145",
      "79": "RND_M_113",
      "80": "RND_M_157",
      "81": "RND_F_022",
      "82": "RND_F_087",
      "83": "RND_M_093",
      "84": "RND_F_077",
      "85": "RND_F_082",
      "86": "RND_M_048",
      "87": "RND_F_029",
      "88": "RND_M_125",
      "89": "RND_F_009",
      "90": "RND_F_066",
      "91": "RND_M_160",
      "92": "RND_M_124",
      "93": "RND_F_045",
      "94": "RND_M_039",
      "95": "RND_M_043",
      "96": "RND_F_104",
      "97": "RND_M_021",
      "98": "RND_F_039",
      "99": "RND_F_112",
      "100": "RND_M_107",
      "101": "RND_F_034",
      "102": "RND_M_072",
      "103": "RND_F_099",
      "104": "RND_M_064",
      "105": "RND_M_096",
      "106": "RND_M_056",
      "107": "RND_M_033",
      "108": "RND_F_037",
      "109": "RND_F_027",
      "110": "RND_M_151",
      "111": "RND_F_061",
      "112": "RND_M_010",
      "113": "RND_M_095",
      "114": "RND_F_075",
      "115": "RND_F_028",
      "116": "RND_F_044",
      "117": "RND_F_111",
      "118": "RND_M_144",
      "119": "RND_F_024",
      "120": "RND_M_134",
      "121": "RND_F_086",
      "122": "RND_M_141",
      "123": "RND_F_005",
      "124": "RND_M_127",
      "125": "RND_M_094",
      "126": "RND_F_069",
      "127": "RND_M_018",
      "128": "RND_M_085",
      "129": "RND_M_028",
      "130": "RND_M_045",
      "131": "RND_F_090",
      "132": "RND_M_097",
      "133": "RND_M_099",
      "134": "RND_M_049",
      "135": "RND_M_019",
      "136": "RND_M_170",
      "137": "RND_M_111",
      "138": "RND_F_048",
      "139": "RND_F_038",
      "140": "RND_F_019",
      "141": "RND_F_097",
      "142": "RND_M_078",
      "143": "RND_M_109",
      "144": "RND_M_086",
      "145": "RND_F_094",
      "146": "RND_M_176",
      "147": "RND_F_030",
      "148": "RND_M_050",
      "149": "RND_M_029",
      "150": "RND_F_108",
      "151": "RND_M_123",
      "152": "RND_M_037",
      "153": "RND_M_061",
      "154": "RND_M_068",
      "155": "RND_M_074",
      "156": "RND_F_095",
      "157": "RND_F_068",
      "158": "RND_F_101",
      "159": "RND_M_166",
      "160": "RND_F_049",
      "161": "RND_F_076",
      "162": "RND_F_059",
      "163": "RND_M_009",
      "164": "RND_F_107",
      "165": "RND_M_120",
      "166": "RND_M_090",
      "167": "RND_M_080",
      "168": "RND_M_058",
      "169": "RND_M_012",
      "170": "RND_F_058",
      "171": "RND_F_083",
      "172": "RND_M_178",
      "173": "RND_F_064",
      "174": "RND_F_040",
      "175": "RND_M_137",
      "176": "RND_F_008",
      "177": "RND_F_016",
      "178": "RND_M_053",
      "179": "RND_M_026",
      "180": "RND_F_113",
      "181": "RND_M_041",
      "182": "RND_F_023",
      "183": "RND_F_046",
      "184": "RND_M_161",
      "185": "RND_M_171",
      "186": "RND_M_146",
      "187": "RND_M_013",
      "188": "RND_F_074",
      "189": "RND_F_089",
      "190": "RND_M_149",
      "191": "RND_M_087",
      "192": "RND_M_092",
      "193": "RND_M_073",
      "194": "RND_M_046",
      "195": "RND_F_055",
      "196": "RND_F_052",
      "197": "RND_M_007",
      "198": "RND_F_093",
      "199": "RND_M_091",
      "200": "RND_M_164",
      "201": "RND_M_040",
      "202": "RND_M_158",
      "203": "RND_M_108",
      "204": "RND_M_101",
      "205": "RND_M_119",
      "206": "RND_F_021",
      "207": "RND_F_012",
      "208": "RND_M_143",
      "209": "RND_M_156",
      "210": "RND_M_054",
      "211": "RND_F_071",
      "212": "RND_F_067",
      "213": "RND_F_043",
      "214": "RND_F_079",
      "215": "RND_F_116",
      "216": "RND_M_136",
      "217": "RND_M_004",
      "218": "RND_F_080",
      "219": "RND_M_005",
      "220": "RND_M_104",
      "221": "RND_M_081",
      "222": "RND_M_036",
      "223": "RND_F_007",
      "224": "RND_M_154",
      "225": "RND_F_088",
      "226": "RND_M_059",
      "227": "RND_F_050",
      "228": "RND_M_022",
      "229": "RND_M_130",
      "230": "RND_M_077",
      "231": "RND_F_084",
      "232": "RND_M_121",
      "233": "RND_M_006",
      "234": "RND_M_129",
      "235": "RND_M_153",
      "236": "RND_F_010",
      "237": "RND_M_174",
      "238": "RND_M_069",
      "239": "RND_F_081",
      "240": "RND_F_065",
      "241": "RND_M_031",
      "242": "RND_M_165",
      "243": "RND_M_168",
      "244": "RND_F_018",
      "245": "RND_M_167",
      "246": "RND_M_044",
      "247": "RND_M_047",
      "248": "RND_M_060",
      "249": "RND_M_159",
      "250": "RND_M_138",
      "251": "RND_M_084",
      "252": "RND_M_076",
      "253": "RND_F_114",
      "254": "RND_M_089",
      "255": "RND_F_096",
      "256": "RND_F_103",
      "257": "RND_M_032",
      "258": "RND_M_102",
      "259": "RND_M_122",
      "260": "RND_F_014",
      "261": "RND_M_067",
      "262": "RND_M_082",
      "263": "RND_M_030",
      "264": "RND_F_032",
      "265": "RND_F_106",
      "266": "RND_F_102",
      "267": "RND_F_054",
      "268": "RND_F_062",
      "269": "RND_M_110",
      "270": "RND_M_014",
      "271": "RND_M_106",
      "272": "RND_F_105",
      "273": "RND_F_041",
      "274": "RND_M_057",
      "275": "RND_M_172",
      "276": "RND_F_117",
      "277": "RND_F_115",
      "278": "RND_M_177",
      "279": "RND_F_031",
      "280": "RND_M_024",
      "281": "RND_M_175",
      "282": "RND_M_011",
      "283": "RND_F_073",
      "284": "RND_F_057",
      "285": "RND_M_088",
      "286": "RND_M_098",
      "287": "RND_M_152",
      "288": "RND_F_100",
      "289": "RND_F_051",
      "290": "RND_F_011",
      "291": "RND_M_025",
      "292": "RND_M_169",
      "293": "RND_M_150",
      "294": "RND_M_017",
      "295": "RND_M_155",
      "296": "RND_M_126",
      "297": "RND_M_052",
      "298": "RND_F_098",
      "299": "RND_M_133",
      "300": "RND_M_034",
      "301": "RND_F_004"
    },
    "character_code": {
      "char_000": "TP_000",
      "char_001": "TP_001",
      "char_002": "TP_002",
      "char_003": "TP_003",
      "char_004": "TP_004",
      "char_005": "TP_005",
      "char_006": "TP_006",
      "char_007": "TP_007",
      "char_008": "TP_008",
      "char_009": "TP_009",
      "char_010": "TP_010",
      "char_011": "TP_011",
      "char_012": "TP_012",
      "char_013": "TP_013",
      "char_014": "TP_014",
      "char_015": "TP_015",
      "char_016": "TP_016",
      "char_017": "TP_017",
      "char_018": "TP_018",
      "char_019": "TP_019",
      "char_020": "TP_021",
      "char_021": "TP_022",
      "char_022": "TP_023",
      "char_023": "TP_024",
      "char_024": "TP_025",
      "char_025": "TP_026",
      "char_026": "TP_027",
      "char_027": "TP_030",
      "char_028": "TP_031",
      "char_029": "TP_033",
      "char_030": "TP_034",
      "char_031": "TP_036",
      "char_032": "TP_038",
      "char_033": "TP_039",
      "char_034": "TP_041",
      "char_035": "TP_042",
      "char_036": "TP_043",
      "char_037": "TP_046",
      "char_038": "TP_047",
      "char_039": "TP_048",
      "char_040": "TP_049",
      "char_041": "TP_070",
      "char_042": "TP_071",
      "char_043": "TP_072",
      "char_044": "TP_073",
      "char_045": "TP_074",
      "char_046": "TP_075",
      "char_047": "TP_076",
      "char_048": "TP_077",
      "char_049": "TP_078",
      "char_050": "TP_079",
      "char_051": "TP_080",
      "char_052": "TP_081",
      "char_053": "TP_082",
      "char_054": "TP_083",
      "char_055": "TP_084",
      "char_056": "TP_085",
      "char_057": "TP_086",
      "char_058": "TP_087",
      "char_059": "TP_088",
      "char_060": "TP_089",
      "char_061": "TP_091",
      "char_062": "TP_093",
      "char_063": "TP_094",
      "char_064": "RND_M_148",
      "char_065": "RND_M_131",
      "char_066": "RND_M_135",
      "char_067": "RND_M_001",
      "char_068": "RND_M_147",
      "char_069": "RND_F_072",
      "char_070": "RND_M_103",
      "char_071": "RND_M_066",
      "char_072": "RND_F_078",
      "char_073": "RND_M_062",
      "char_074": "RND_F_026",
      "char_075": "RND_M_128",
